In [2]:
import pandas as pd
import os

# Set path to YouTube file
yt_path = r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\merged\youtube_comments_merged.csv"

# Load it
yt_df = pd.read_csv(yt_path)

# Show shape and first few rows
print("🔹 YouTube Shape:", yt_df.shape)
print("🔹 YouTube Columns:", yt_df.columns.tolist())
yt_df.head(5)

🔹 YouTube Shape: (62453, 10)
🔹 YouTube Columns: ['username', 'video_id', 'comment_url', 'time_posted', 'time_posted_parsed', 'comment', 'comment_original', 'like_count', 'is_duplicate_comment', 'source_file']

,username,video_id,comment_url,time_posted,time_posted_parsed,comment,comment_original,like_count,is_duplicate_comment,source_file
0,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,Pinned by @SPIRITUALSo,NaN,GAZER GAZER in the Building man Siiiiiiiiiiiii...,GAZER GAZER in the Building man Siiiiiiiiiiiii...,943,NaN,youtube (1)_cleaned.csv
1,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,@TheAngelicFrequency,NaN,"Once you become aware, you can never go back! ...","Once you become aware, you can never go back! ...",372,NaN,youtube (1)_cleaned.csv
2,1 month ago (edited),V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,@Kod1795,NaN,Y'all noticed how time be going by like crazy?,Y'all noticed how time be going by like crazy?,815,NaN,youtube (1)_cleaned.csv
3,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,@saintyaza,NaN,I feel this deeply.. I've become extremely det...,I feel this deeply.. I've become extremely det...,177,NaN,youtube (1)_cleaned.csv
4,1 month ago (edited),V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,@jacobbrent9839,NaN,"semen rentention, meditation, eating healthy, ...","semen rentention, meditation, eating healthy, ...",666,NaN,youtube (1)_cleaned.csv

clean the youtube username to become actual username and do the same for the time posted column

In [3]:
# Correct column swap: username and time_posted were flipped
yt_df = yt_df.rename(columns={
    'username': 'time_posted_raw',
    'time_posted': 'username'
})

# Drop broken or irrelevant columns
yt_df = yt_df.drop(columns=['time_posted_parsed', 'is_duplicate_comment'])

# Add platform and source_type
yt_df['platform'] = 'youtube'
yt_df['source_type'] = 'pop_culture'

# Reorder for clarity (optional)
yt_df = yt_df[[
    'username', 'time_posted_raw', 'video_id', 'comment_url',
    'comment', 'comment_original', 'like_count', 'source_file',
    'platform', 'source_type'
]]

# Preview cleaned YouTube data
yt_df.head(3)

,username,time_posted_raw,video_id,comment_url,comment,comment_original,like_count,source_file,platform,source_type
0,Pinned by @SPIRITUALSo,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,GAZER GAZER in the Building man Siiiiiiiiiiiii...,GAZER GAZER in the Building man Siiiiiiiiiiiii...,943,youtube (1)_cleaned.csv,youtube,pop_culture
1,@TheAngelicFrequency,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,"Once you become aware, you can never go back! ...","Once you become aware, you can never go back! ...",372,youtube (1)_cleaned.csv,youtube,pop_culture
2,@Kod1795,1 month ago (edited),V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,Y'all noticed how time be going by like crazy?,Y'all noticed how time be going by like crazy?,815,youtube (1)_cleaned.csv,youtube,pop_culture

In [4]:
# Load Reddit file
reddit_path = r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\merged\reddit_comments_merged.csv"
reddit_df = pd.read_csv(reddit_path)

# Show shape and preview structure
print("🔹 Reddit Shape:", reddit_df.shape)
print("🔹 Reddit Columns:", reddit_df.columns.tolist())
reddit_df.head(5)

🔹 Reddit Shape: (29972, 12)
🔹 Reddit Columns: ['username', 'subreddit', 'comment_url', 'time_posted', 'time_posted_parsed', 'comment', 'comment_original', 'post_title', 'post_body', 'data_type', 'source_file', 'comment_author']

,username,subreddit,comment_url,time_posted,time_posted_parsed,comment,comment_original,post_title,post_body,data_type,source_file,comment_author
0,belltowerbats,NaN,[object Object],6y ago,NaN,[X] I'm in this post and I don't like it,NaN,NaN,"I relate to this a lot, although I’m far less ...",comment,reddit (1).csv,NaN
1,worstusernameever00,NaN,NaN,6y ago,NaN,NaN,NaN,NaN,"Yes, I feel like an outsider a lot. Your post ...",comment,reddit (1).csv,NaN
2,faustian1,NaN,[object Object],6y ago,NaN,NaN,NaN,NaN,"Yes sir, I think you nailed it with that descr...",comment,reddit (1).csv,NaN
3,[deleted],NaN,[object Object],6y ago,NaN,"When I'm going out alone, that feeling of bein...",NaN,NaN,"Yep, I can relate, I once went to a bar and on...",comment,reddit (1).csv,NaN
4,[deleted],NaN,[object Object],6y ago,NaN,NaN,NaN,NaN,Definitely. It can be a lonely world out there...,comment,reddit (1).csv,NaN

| Column Name          | Status                       | Notes                                                             |
| -------------------- | ---------------------------- | ----------------------------------------------------------------- |
| `username`           | ✅ OK                         | Contains usernames like `belltowerbats` or `[deleted]`. Valid.    |
| `subreddit`          | ❌ All NaN                    | Useless in current state — drop it unless recoverable.            |
| `comment_url`        | ❌ Value is `[object Object]` | Broken — likely from scraping JSON or HTML badly. Drop it.        |
| `time_posted`        | ⚠️ "6y ago"                  | Relative, not parsed. `time_posted_parsed` is also empty.         |
| `time_posted_parsed` | ❌ All NaN                    | Useless — drop.                                                   |
| `comment`            | ⚠️ Mixed                     | Some rows valid, others `NaN`. We'll need to filter out bad ones. |
| `comment_original`   | ⚠️ Mostly NaN                | Probably wasn’t captured during scraping. Can drop if fully NaN.  |
| `post_title`         | ✅ Good                       | Valuable for context. Keep.                                       |
| `post_body`          | ✅ Good                       | Keep. This is often where the abstract concepts are embedded.     |
| `data_type`          | ⚠️ All `"comment"`           | Redundant for our use — drop unless multi-type content expected.  |
| `source_file`        | ✅ Fine                       | Optional for audit trail. Keep or drop.                           |
| `comment_author`     | ❌ All NaN                    | Probably a duplicate of `username`, broken — drop.                |

In [5]:
# Drop broken/useless columns
reddit_df = reddit_df.drop(columns=[
    'subreddit', 'comment_url', 'time_posted_parsed',
    'comment_original', 'data_type', 'comment_author'
])

# Drop rows with missing comments
reddit_df = reddit_df[reddit_df['comment'].notna()].copy()

# Add platform and source_type
reddit_df['platform'] = 'reddit'
reddit_df['source_type'] = 'pop_culture'

# Optional: reorder columns
reddit_df = reddit_df[[
    'username', 'time_posted', 'comment', 'post_title', 'post_body',
    'source_file', 'platform', 'source_type'
]]

# Preview cleaned Reddit data
reddit_df.head(3)

,username,time_posted,comment,post_title,post_body,source_file,platform,source_type
0,belltowerbats,6y ago,[X] I'm in this post and I don't like it,NaN,"I relate to this a lot, although I’m far less ...",reddit (1).csv,reddit,pop_culture
3,[deleted],6y ago,"When I'm going out alone, that feeling of bein...",NaN,"Yep, I can relate, I once went to a bar and on...",reddit (1).csv,reddit,pop_culture
5,Sheol_,6y ago,"I am in the same boat as you are, know many pe...",NaN,"You can never be too nice, and being nice isn'...",reddit (1).csv,reddit,pop_culture

In [7]:
# Load Instagram file
ig_path = r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\merged\instagram_comments_merged.csv"
ig_df = pd.read_csv(ig_path)

print("🔹 Instagram Shape:", ig_df.shape)
print("🔹 Instagram Columns:", ig_df.columns.tolist())
ig_df.head(5)

🔹 Instagram Shape: (9993, 15)
🔹 Instagram Columns: ['username', 'profile_url', 'comment_url', 'time_posted', 'time_posted_parsed', 'comment', 'comment_original', 'like_count', 'is_duplicate_comment', 'post_id', 'post_title', 'post_body', 'video_id', 'likes', 'reply_count']

,username,profile_url,comment_url,time_posted,time_posted_parsed,comment,comment_original,like_count,is_duplicate_comment,post_id,post_title,post_body,video_id,likes,reply_count
0,snakebbite,https://www.instagram.com/snakebbite/,https://www.instagram.com/p/DFauEcPMP-0/c/1786...,22w,NaN,i’m sorry? god is all powerful but needs a chi...,i’m sorry? god is all powerful but needs a chi...,26328.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,malevolent_vi,https://www.instagram.com/malevolent_vi/,https://www.instagram.com/p/DFauEcPMP-0/c/1828...,22w,NaN,cOuLd tHeRe bE a pUrPoSe tO iT?,cOuLd tHeRe bE a pUrPoSe tO iT?,9217.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,drone.or.fowl,https://www.instagram.com/drone.or.fowl/,https://www.instagram.com/p/DFauEcPMP-0/c/1805...,21w,NaN,Only religion can try to twist a child dying a...,Only religion can try to twist a child dying a...,4706.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,eloisatsatsas,https://www.instagram.com/eloisatsatsas/,https://www.instagram.com/p/DFauEcPMP-0/c/1802...,22w,NaN,if god is giving children Leukaemia to bring t...,if god is giving children Leukaemia to bring t...,10037.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,justforkix_mr,https://www.instagram.com/justforkix_mr/,https://www.instagram.com/p/DFauEcPMP-0/c/1785...,22w,NaN,They must get exhausted from the mental gymnas...,They must get exhausted from the mental gymnas...,5632.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

| Column Name                                                              | Status              | Notes                                                                  |
| ------------------------------------------------------------------------ | ------------------- | ---------------------------------------------------------------------- |
| `username`                                                               | ✅ Good              | Valid handles like `snakebbite`, no issues.                            |
| `profile_url`                                                            | ⚠️ Redundant        | Optional. May drop unless you're linking back to profiles.             |
| `comment_url`                                                            | ✅ Good              | Points to specific Instagram comments. Useful if keeping traceability. |
| `time_posted`                                                            | ⚠️ `"22w"`, `"21w"` | Relative time format. Can be kept as-is or dropped.                    |
| `time_posted_parsed`                                                     | ❌ All `NaN`         | Broken parsing — drop.                                                 |
| `comment`                                                                | ✅ Good              | Cleaned and normalized. Keep.                                          |
| `comment_original`                                                       | ✅ Good              | Original case — valuable. Keep.                                        |
| `like_count`                                                             | ✅ Good              | Float, but meaningful (e.g., `26328.0`). Keep.                         |
| `is_duplicate_comment`                                                   | ❌ All `NaN`         | Broken — drop.                                                         |
| `post_id`, `post_title`, `post_body`, `video_id`, `likes`, `reply_count` | ❌ All `NaN`         | Scraper likely didn't retrieve this data — **drop all**.               |

In [9]:
# Drop broken/unnecessary columns
ig_df = ig_df.drop(columns=[
    'time_posted_parsed', 'is_duplicate_comment', 'post_id', 'post_title',
    'post_body', 'video_id', 'likes', 'reply_count'
])

# Add platform and source_type
ig_df['platform'] = 'instagram'
ig_df['source_type'] = 'pop_culture'

# Optional: drop profile_url if not needed
# ig_df = ig_df.drop(columns=['profile_url'])

# Reorder columns
ig_df = ig_df[[
    'username', 'time_posted', 'comment', 'comment_original',
    'like_count', 'comment_url', 'profile_url',
    'platform', 'source_type'
]]

# Preview result
ig_df.head(3)

,username,time_posted,comment,comment_original,like_count,comment_url,profile_url,platform,source_type
0,snakebbite,22w,i’m sorry? god is all powerful but needs a chi...,i’m sorry? god is all powerful but needs a chi...,26328.0,https://www.instagram.com/p/DFauEcPMP-0/c/1786...,https://www.instagram.com/snakebbite/,instagram,pop_culture
1,malevolent_vi,22w,cOuLd tHeRe bE a pUrPoSe tO iT?,cOuLd tHeRe bE a pUrPoSe tO iT?,9217.0,https://www.instagram.com/p/DFauEcPMP-0/c/1828...,https://www.instagram.com/malevolent_vi/,instagram,pop_culture
2,drone.or.fowl,21w,Only religion can try to twist a child dying a...,Only religion can try to twist a child dying a...,4706.0,https://www.instagram.com/p/DFauEcPMP-0/c/1805...,https://www.instagram.com/drone.or.fowl/,instagram,pop_culture

In [10]:
# Load TikTok file
tiktok_path = r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\merged\tiktok_comments_merged.csv"
tt_df = pd.read_csv(tiktok_path)

print("🔹 TikTok Shape:", tt_df.shape)
print("🔹 TikTok Columns:", tt_df.columns.tolist())
tt_df.head(5)

🔹 TikTok Shape: (2114, 7)
🔹 TikTok Columns: ['username', 'comment', 'like_count', 'time_posted', 'comment_url', 'comment_original', 'is_duplicate_comment']

,username,comment,like_count,time_posted,comment_url,comment_original,is_duplicate_comment
0,cryswanto,too much awareness can lead to depressed bro ngl,17311,2024-12-10 23:53:58+00:00,https://www.tiktok.com/@pontificalp/video/7446...,too much awareness can lead to depressed bro ngl,False
1,king.nothing83,we suffer more in our imagination than in reality,4322,2024-12-13 10:01:01+00:00,https://www.tiktok.com/@pontificalp/video/7446...,We suffer more in our imagination than in reality,False
2,milthonrod24_life,ur changing my whole perspective on life,2380,2024-12-10 21:37:41+00:00,https://www.tiktok.com/@pontificalp/video/7446...,Ur changing my whole perspective on life,False
3,alex.prikna,beautiful perspective,489,2024-12-10 17:28:20+00:00,https://www.tiktok.com/@pontificalp/video/7446...,Beautiful perspective,False
4,user9990860,im torn between wanting to know more and wishi...,1587,2024-12-13 00:05:28+00:00,https://www.tiktok.com/@pontificalp/video/7446...,I’m torn between wanting to know more and wish...,False

mostly all good, except one

In [12]:
# Add missing columns
tt_df['profile_url'] = None  # TikTok profile URL not available
tt_df['platform'] = 'tiktok'
tt_df['source_type'] = 'pop_culture'

# Select and reorder columns to match the standard
tt_df_cleaned = tt_df[[
    'username', 'time_posted', 'comment', 'comment_original',
    'like_count', 'comment_url', 'profile_url',
    'platform', 'source_type'
]]

print("🔹 Cleaned TikTok Shape:", tt_df_cleaned.shape)
print("🔹 Cleaned TikTok Columns:", tt_df_cleaned.columns.tolist())
tt_df_cleaned.head(3)

🔹 Cleaned TikTok Shape: (2114, 9)
🔹 Cleaned TikTok Columns: ['username', 'time_posted', 'comment', 'comment_original', 'like_count', 'comment_url', 'profile_url', 'platform', 'source_type']

,username,time_posted,comment,comment_original,like_count,comment_url,profile_url,platform,source_type
0,cryswanto,2024-12-10 23:53:58+00:00,too much awareness can lead to depressed bro ngl,too much awareness can lead to depressed bro ngl,17311,https://www.tiktok.com/@pontificalp/video/7446...,None,tiktok,pop_culture
1,king.nothing83,2024-12-13 10:01:01+00:00,we suffer more in our imagination than in reality,We suffer more in our imagination than in reality,4322,https://www.tiktok.com/@pontificalp/video/7446...,None,tiktok,pop_culture
2,milthonrod24_life,2024-12-10 21:37:41+00:00,ur changing my whole perspective on life,Ur changing my whole perspective on life,2380,https://www.tiktok.com/@pontificalp/video/7446...,None,tiktok,pop_culture

#### Let's now merge all of the data

In [13]:
import pandas as pd

# Load each cleaned DataFrame (adjust paths as needed)
reddit_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/reddit_comments_merged.csv")
youtube_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/youtube_comments_merged.csv")
instagram_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/instagram_comments_merged.csv")
tiktok_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/tiktok_comments_merged.csv")

# Concatenate all datasets
merged_df = pd.concat([reddit_df, youtube_df, instagram_df, tiktok_df], ignore_index=True)

# Preview
print("✅ Final Merged Shape:", merged_df.shape)
print("✅ Columns:", merged_df.columns.tolist())
merged_df.head(3)

# Save to disk
merged_df.to_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/final_merged_all_comments.csv", index=False)

✅ Final Merged Shape: (104532, 19)
✅ Columns: ['username', 'subreddit', 'comment_url', 'time_posted', 'time_posted_parsed', 'comment', 'comment_original', 'post_title', 'post_body', 'data_type', 'source_file', 'comment_author', 'video_id', 'like_count', 'is_duplicate_comment', 'profile_url', 'post_id', 'likes', 'reply_count']

In [15]:
reddit_raw = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/reddit_comments_merged.csv")
print("🔍 Reddit Columns:", reddit_raw.columns.tolist())
reddit_raw.head(3)

🔍 Reddit Columns: ['username', 'subreddit', 'comment_url', 'time_posted', 'time_posted_parsed', 'comment', 'comment_original', 'post_title', 'post_body', 'data_type', 'source_file', 'comment_author']

,username,subreddit,comment_url,time_posted,time_posted_parsed,comment,comment_original,post_title,post_body,data_type,source_file,comment_author
0,belltowerbats,NaN,[object Object],6y ago,NaN,[X] I'm in this post and I don't like it,NaN,NaN,"I relate to this a lot, although I’m far less ...",comment,reddit (1).csv,NaN
1,worstusernameever00,NaN,NaN,6y ago,NaN,NaN,NaN,NaN,"Yes, I feel like an outsider a lot. Your post ...",comment,reddit (1).csv,NaN
2,faustian1,NaN,[object Object],6y ago,NaN,NaN,NaN,NaN,"Yes sir, I think you nailed it with that descr...",comment,reddit (1).csv,NaN

In [16]:
# Load original Reddit data
reddit_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/reddit_comments_merged.csv")

# Fix missing or broken fields
reddit_df["like_count"] = 0
reddit_df["profile_url"] = None
reddit_df["platform"] = "reddit"
reddit_df["source_type"] = "pop_culture"

# Fix the comment_url if it's just '[object Object]'
reddit_df["comment_url"] = None  # or set to actual links if you can reconstruct them later

# Only keep the final set of required columns
final_columns = [
    'username', 'time_posted', 'comment', 'comment_original',
    'like_count', 'comment_url', 'profile_url', 'platform', 'source_type'
]
reddit_df = reddit_df[final_columns]

# Preview
print("✅ Reddit (Fixed) Shape:", reddit_df.shape)
reddit_df.head(3)

✅ Reddit (Fixed) Shape: (29972, 9)

,username,time_posted,comment,comment_original,like_count,comment_url,profile_url,platform,source_type
0,belltowerbats,6y ago,[X] I'm in this post and I don't like it,NaN,0,None,None,reddit,pop_culture
1,worstusernameever00,6y ago,NaN,NaN,0,None,None,reddit,pop_culture
2,faustian1,6y ago,NaN,NaN,0,None,None,reddit,pop_culture

In [17]:
youtube_path = "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/youtube_comments_merged.csv"
youtube_df = pd.read_csv(youtube_path)
print("📄 YouTube Columns:", youtube_df.columns.tolist())
youtube_df.head(2)

📄 YouTube Columns: ['username', 'video_id', 'comment_url', 'time_posted', 'time_posted_parsed', 'comment', 'comment_original', 'like_count', 'is_duplicate_comment', 'source_file']

,username,video_id,comment_url,time_posted,time_posted_parsed,comment,comment_original,like_count,is_duplicate_comment,source_file
0,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,Pinned by @SPIRITUALSo,NaN,GAZER GAZER in the Building man Siiiiiiiiiiiii...,GAZER GAZER in the Building man Siiiiiiiiiiiii...,943,NaN,youtube (1)_cleaned.csv
1,1 month ago,V9pQvbZXBb4,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,@TheAngelicFrequency,NaN,"Once you become aware, you can never go back! ...","Once you become aware, you can never go back! ...",372,NaN,youtube (1)_cleaned.csv

In [18]:
# Reload YouTube Data
youtube_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/youtube_comments_merged.csv")

# Rename and align columns
youtube_df_cleaned = pd.DataFrame({
    'username': youtube_df['time_posted'],  # Actually contains usernames
    'time_posted': youtube_df['comment_url'],  # Actually contains timestamps
    'comment': youtube_df['comment'],
    'comment_original': youtube_df['comment_original'],
    'like_count': youtube_df['like_count'],
    'comment_url': youtube_df['comment_url'],
    'profile_url': None,  # Not available
    'platform': 'youtube',
    'source_type': 'pop_culture'
})

print("✅ YouTube (Fixed) Shape:", youtube_df_cleaned.shape)
youtube_df_cleaned.head(2)

✅ YouTube (Fixed) Shape: (62453, 9)

,username,time_posted,comment,comment_original,like_count,comment_url,profile_url,platform,source_type
0,Pinned by @SPIRITUALSo,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,GAZER GAZER in the Building man Siiiiiiiiiiiii...,GAZER GAZER in the Building man Siiiiiiiiiiiii...,943,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,None,youtube,pop_culture
1,@TheAngelicFrequency,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,"Once you become aware, you can never go back! ...","Once you become aware, you can never go back! ...",372,https://www.youtube.com/watch?v=V9pQvbZXBb4&lc...,None,youtube,pop_culture

In [25]:
import pandas as pd

# Load cleaned Instagram CSV
insta_cleaned = pd.read_csv(
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/instagram_comments_merged.csv"
)

# Preview shape and first few rows
print(f"✅ Instagram (Cleaned) Shape: {insta_cleaned.shape}")
print(insta_cleaned.head())

✅ Instagram (Cleaned) Shape: (9993, 15)
        username                               profile_url  \
0     snakebbite     https://www.instagram.com/snakebbite/
1  malevolent_vi  https://www.instagram.com/malevolent_vi/
2  drone.or.fowl  https://www.instagram.com/drone.or.fowl/
3  eloisatsatsas  https://www.instagram.com/eloisatsatsas/
4  justforkix_mr  https://www.instagram.com/justforkix_mr/

                                         comment_url time_posted  \
0  https://www.instagram.com/p/DFauEcPMP-0/c/1786...         22w
1  https://www.instagram.com/p/DFauEcPMP-0/c/1828...         22w
2  https://www.instagram.com/p/DFauEcPMP-0/c/1805...         21w
3  https://www.instagram.com/p/DFauEcPMP-0/c/1802...         22w
4  https://www.instagram.com/p/DFauEcPMP-0/c/1785...         22w

  time_posted_parsed                                            comment  \
0                NaN  i’m sorry? god is all powerful but needs a chi...
1                NaN                    cOuLd tHeRe bE a pUrPoSe tO iT?
2                NaN  Only religion can try to twist a child dying a...
3                NaN  if god is giving children Leukaemia to bring t...
4                NaN  They must get exhausted from the mental gymnas...

                                    comment_original like_count  \
0  i’m sorry? god is all powerful but needs a chi...    26328.0
1                    cOuLd tHeRe bE a pUrPoSe tO iT?     9217.0
2  Only religion can try to twist a child dying a...     4706.0
3  if god is giving children Leukaemia to bring t...    10037.0
4  They must get exhausted from the mental gymnas...     5632.0

   is_duplicate_comment  post_id  post_title  post_body video_id  likes  \
0                   NaN      NaN         NaN        NaN      NaN    NaN
1                   NaN      NaN         NaN        NaN      NaN    NaN
2                   NaN      NaN         NaN        NaN      NaN    NaN
3                   NaN      NaN         NaN        NaN      NaN    NaN
4                   NaN      NaN         NaN        NaN      NaN    NaN

   reply_count
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

In [26]:
insta_cleaned_fixed = insta_cleaned.copy()

# Drop unused or all-NaN columns
cols_to_drop = ['post_id', 'post_title', 'post_body', 'video_id', 'likes', 'reply_count', 'is_duplicate_comment']
insta_cleaned_fixed.drop(columns=cols_to_drop, inplace=True)

# Add final columns
insta_cleaned_fixed['platform'] = 'instagram'
insta_cleaned_fixed['source_type'] = 'pop_culture'

# Reorder columns for consistency
insta_cleaned_fixed = insta_cleaned_fixed[[
    'username', 'time_posted', 'comment', 'comment_original',
    'like_count', 'comment_url', 'profile_url', 'platform', 'source_type'
]]

# Save fixed version
insta_cleaned_fixed.to_csv(
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/instagram_comments_merged.csv",
    index=False
)

print(f"✅ Instagram (Fixed) Shape: {insta_cleaned_fixed.shape}")

✅ Instagram (Fixed) Shape: (9993, 9)

In [28]:
import pandas as pd

# Load cleaned Instagram CSV
insta_cleaned = pd.read_csv(
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/tiktok_comments_merged.csv"
)

# Preview shape and first few rows
print(f"✅ Tiktok (Cleaned) Shape: {insta_cleaned.shape}")
print(insta_cleaned.head())

✅ Tiktok (Cleaned) Shape: (2114, 7)
            username                                            comment  \
0          cryswanto   too much awareness can lead to depressed bro ngl
1     king.nothing83  we suffer more in our imagination than in reality
2  milthonrod24_life           ur changing my whole perspective on life
3        alex.prikna                              beautiful perspective
4        user9990860  im torn between wanting to know more and wishi...

   like_count                time_posted  \
0       17311  2024-12-10 23:53:58+00:00
1        4322  2024-12-13 10:01:01+00:00
2        2380  2024-12-10 21:37:41+00:00
3         489  2024-12-10 17:28:20+00:00
4        1587  2024-12-13 00:05:28+00:00

                                         comment_url  \
0  https://www.tiktok.com/@pontificalp/video/7446...
1  https://www.tiktok.com/@pontificalp/video/7446...
2  https://www.tiktok.com/@pontificalp/video/7446...
3  https://www.tiktok.com/@pontificalp/video/7446...
4  https://www.tiktok.com/@pontificalp/video/7446...

                                    comment_original  is_duplicate_comment
0   too much awareness can lead to depressed bro ngl                 False
1  We suffer more in our imagination than in reality                 False
2           Ur changing my whole perspective on life                 False
3                              Beautiful perspective                 False
4  I’m torn between wanting to know more and wish...                 False

In [30]:
import pandas as pd

# ✅ Corrected TikTok path using absolute path
tiktok_path = "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/tiktok_comments_merged.csv"

# Load the cleaned TikTok file
tiktok_df = pd.read_csv(tiktok_path)

# Fix formatting
tiktok_df['profile_url'] = "https://www.tiktok.com/@" + tiktok_df['username'].astype(str)

# Add platform and source type columns
tiktok_df['platform'] = 'tiktok'
tiktok_df['source_type'] = 'pop_culture'

# Reorder columns to match the others
tiktok_df = tiktok_df[['username', 'time_posted', 'comment', 'comment_original', 'like_count',
                       'comment_url', 'profile_url', 'platform', 'source_type']]

# Preview
print("✅ TikTok (Fixed) Shape:", tiktok_df.shape)
tiktok_df.head(2)

✅ TikTok (Fixed) Shape: (2114, 9)

,username,time_posted,comment,comment_original,like_count,comment_url,profile_url,platform,source_type
0,cryswanto,2024-12-10 23:53:58+00:00,too much awareness can lead to depressed bro ngl,too much awareness can lead to depressed bro ngl,17311,https://www.tiktok.com/@pontificalp/video/7446...,https://www.tiktok.com/@cryswanto,tiktok,pop_culture
1,king.nothing83,2024-12-13 10:01:01+00:00,we suffer more in our imagination than in reality,We suffer more in our imagination than in reality,4322,https://www.tiktok.com/@pontificalp/video/7446...,https://www.tiktok.com/@king.nothing83,tiktok,pop_culture

#### Merge all 4 datasets

In [31]:
# Load cleaned files
instagram_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/instagram_comments_merged.csv")
reddit_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/reddit_comments_merged.csv")
youtube_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/youtube_comments_merged.csv")
tiktok_df = pd.read_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/tiktok_comments_merged.csv")

# Combine all
pop_culture_combined = pd.concat([instagram_df, reddit_df, youtube_df, tiktok_df], ignore_index=True)

# Preview and save
print("✅ Combined Pop Culture Shape:", pop_culture_combined.shape)
pop_culture_combined.to_csv("C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/pop_culture_combined.csv", index=False)

✅ Combined Pop Culture Shape: (104532, 18)

In [1]:
import pandas as pd

# List of pop culture file paths
paths = [
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/instagram_comments_merged.csv",
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/reddit_comments_merged.csv",
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/tiktok_comments_merged.csv",
    "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/youtube_comments_merged.csv"
]

# Load and concatenate
dfs = [pd.read_csv(p) for p in paths]
df_merged = pd.concat(dfs, ignore_index=True)

# Save to new CSV
output_path = "C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/popculture_texts_merged.csv"
df_merged.to_csv(output_path, index=False)

print("✅ Pop culture data merged and saved to:", output_path)

✅ Pop culture data merged and saved to: C:/Users/USER/Desktop/Projects/philosophy_and_popculture/data/pop_texts/merged/popculture_texts_merged.csv