In [195]:
from pathlib import Path
import pandas as pd

# Set folder paths
raw_folder = Path(r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\instagram\instagram_comments")
cleaned_folder = Path(r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\instagram\instagram_comments_cleaned")
cleaned_folder.mkdir(parents=True, exist_ok=True)

# List all raw files (CSV and Excel)
raw_files = sorted([f for f in raw_folder.iterdir() if f.suffix in ['.csv', '.xlsx']])
cleaned_files = {f.stem.replace('_cleaned', '') for f in cleaned_folder.glob("*_cleaned.csv")}

# Get next unprocessed file
next_file = None
for file in raw_files:
    name = file.stem
    if name not in cleaned_files:
        next_file = file
        break

print(f"👉 Next file to clean: {next_file.name}" if next_file else "✅ All files cleaned.")

✅ All files cleaned.

In [192]:
# Load the selected file
input_path = next_file

if input_path.suffix == '.csv':
    df = pd.read_csv(input_path, dtype=str, encoding='utf-8', engine='python', on_bad_lines='skip')
elif input_path.suffix == '.xlsx':
    df = pd.read_excel(input_path, dtype=str, engine='openpyxl')
else:
    raise ValueError(f"🛑 Unsupported file type: {input_path.suffix}")

print(f"\n📂 Loaded: {input_path.name}")
print("🧾 Columns:", df.columns.tolist())
df.head()

📂 Loaded: instagram (8).xlsx
🧾 Columns: ['x1i10hfl href', 'html-span', 'html-span 2', 'html-span 3', 'x1i10hfl href 2', 'html-span 4', 'html-span 5', 'html-span 6', 'x1i10hfl href 3', 'html-span 7', 'html-span 8', 'html-span 9', 'x1i10hfl href 4', 'html-span 10', 'html-span 11', 'html-span 12']

,x1i10hfl href,html-span,html-span 2,html-span 3,x1i10hfl href 2,html-span 4,html-span 5,html-span 6,x1i10hfl href 3,html-span 7,html-span 8,html-span 9,x1i10hfl href 4,html-span 10,html-span 11,html-span 12
0,https://www.instagram.com/cosmicskeptic/reel/C...,170K,"9,862",5.6M,https://www.instagram.com/cosmicskeptic/reel/C...,"7,263",705,428K,https://www.instagram.com/cosmicskeptic/reel/C...,12.6K,675,653K,https://www.instagram.com/cosmicskeptic/reel/C...,"6,566","1,672",295K
1,https://www.instagram.com/cosmicskeptic/reel/C...,"3,813",394,197K,https://www.instagram.com/cosmicskeptic/reel/C...,19.9K,"1,621",1.1M,https://www.instagram.com/cosmicskeptic/reel/C...,58.6K,"1,324",1.3M,https://www.instagram.com/cosmicskeptic/reel/C...,"2,220",12,92.9K
2,https://www.instagram.com/cosmicskeptic/reel/C...,"2,385",18,90.9K,https://www.instagram.com/cosmicskeptic/reel/C...,"4,908",403,250K,https://www.instagram.com/cosmicskeptic/reel/C...,14.4K,"1,285",738K,https://www.instagram.com/cosmicskeptic/reel/C...,11.3K,263,390K
3,https://www.instagram.com/cosmicskeptic/reel/C...,"4,668",337,168K,https://www.instagram.com/cosmicskeptic/reel/C...,"3,748",257,154K,https://www.instagram.com/cosmicskeptic/reel/C...,"3,735",108,137K,https://www.instagram.com/cosmicskeptic/reel/C...,19.9K,242,837K
4,https://www.instagram.com/cosmicskeptic/reel/C...,20.4K,930,649K,https://www.instagram.com/cosmicskeptic/reel/C...,17.4K,"2,527",414K,https://www.instagram.com/cosmicskeptic/reel/C...,12.3K,430,406K,https://www.instagram.com/cosmicskeptic/reel/C...,34.6K,434,1.1M

In [193]:
# Update column mapping for reel metrics
column_map.update({
    'x1i10hfl href': 'reel_url_1',
    'html-span': 'views_1', 
    'html-span 2': 'likes_1',
    'html-span 3': 'comments_1',
    'x1i10hfl href 2': 'reel_url_2',
    'html-span 4': 'views_2',
    'html-span 5': 'likes_2',
    'html-span 6': 'comments_2',
    'x1i10hfl href 3': 'reel_url_3',
    'html-span 7': 'views_3',
    'html-span 8': 'likes_3',
    'html-span 9': 'comments_3',
    'x1i10hfl href 4': 'reel_url_4',
    'html-span 10': 'views_4',
    'html-span 11': 'likes_4',
    'html-span 12': 'comments_4'
})

# Apply mapping to existing columns
existing = [col for col in df.columns if col in column_map]
df = df.rename(columns={col: column_map[col] for col in existing})

print("✅ Columns after renaming:")
display(df.head())

✅ Columns after renaming:

,reel_url_1,views_1,likes_1,comments_1,reel_url_2,views_2,likes_2,comments_2,reel_url_3,views_3,likes_3,comments_3,reel_url_4,views_4,likes_4,comments_4
0,https://www.instagram.com/cosmicskeptic/reel/C...,170K,"9,862",5.6M,https://www.instagram.com/cosmicskeptic/reel/C...,"7,263",705,428K,https://www.instagram.com/cosmicskeptic/reel/C...,12.6K,675,653K,https://www.instagram.com/cosmicskeptic/reel/C...,"6,566","1,672",295K
1,https://www.instagram.com/cosmicskeptic/reel/C...,"3,813",394,197K,https://www.instagram.com/cosmicskeptic/reel/C...,19.9K,"1,621",1.1M,https://www.instagram.com/cosmicskeptic/reel/C...,58.6K,"1,324",1.3M,https://www.instagram.com/cosmicskeptic/reel/C...,"2,220",12,92.9K
2,https://www.instagram.com/cosmicskeptic/reel/C...,"2,385",18,90.9K,https://www.instagram.com/cosmicskeptic/reel/C...,"4,908",403,250K,https://www.instagram.com/cosmicskeptic/reel/C...,14.4K,"1,285",738K,https://www.instagram.com/cosmicskeptic/reel/C...,11.3K,263,390K
3,https://www.instagram.com/cosmicskeptic/reel/C...,"4,668",337,168K,https://www.instagram.com/cosmicskeptic/reel/C...,"3,748",257,154K,https://www.instagram.com/cosmicskeptic/reel/C...,"3,735",108,137K,https://www.instagram.com/cosmicskeptic/reel/C...,19.9K,242,837K
4,https://www.instagram.com/cosmicskeptic/reel/C...,20.4K,930,649K,https://www.instagram.com/cosmicskeptic/reel/C...,17.4K,"2,527",414K,https://www.instagram.com/cosmicskeptic/reel/C...,12.3K,430,406K,https://www.instagram.com/cosmicskeptic/reel/C...,34.6K,434,1.1M

In [194]:
def convert_instagram_metric(value):
    """Convert Instagram metrics (1K -> 1000, 1M -> 1000000)"""
    if pd.isna(value):
        return 0
    value = str(value).replace(',', '')
    if 'K' in value:
        return int(float(value.replace('K', '')) * 1000
    elif 'M' in value:
        return int(float(value.replace('M', '')) * 1000000
    try:
        return int(float(value))
    except:
        return 0

# Convert all metric columns
metric_cols = [col for col in df.columns if any(x in col for x in ['views', 'likes', 'comments'])]
for col in metric_cols:
    df[col] = df[col].apply(convert_instagram_metric)

print("✅ Metrics converted to integers:")
display(df.head())

SyntaxError: invalid syntax (1348660658.py, line 8)

In [190]:
# Custom column mapping for reel metrics
column_map.update({
    'x1i10hfl href': 'reel_url',
    'html-span': 'views',
    'html-span 2': 'likes',
    'html-span 3': 'comments',
    'x1i10hfl href 2': 'reel_url_2', 
    'html-span 4': 'views_2',
    'html-span 5': 'likes_2',
    'html-span 6': 'comments_2',
    'x1i10hfl href 3': 'reel_url_3',
    'html-span 7': 'views_3',
    'html-span 8': 'likes_3',
    'html-span 9': 'comments_3',
    'x1i10hfl href 4': 'reel_url_4',
    'html-span 10': 'views_4',
    'html-span 11': 'likes_4',
    'html-span 12': 'comments_4'
})

# Apply mapping
existing = [col for col in df.columns if col in column_map]
df = df.rename(columns={col: column_map[col] for col in existing if col in df.columns})

print("✅ Columns after renaming:", df.columns.tolist())
df.head()

✅ Columns after renaming: ['reel_url_1', 'views_1', 'likes_1', 'comments_1', 'reel_url_2', 'views_2', 'likes_2', 'comments_2', 'reel_url_3', 'views_3', 'likes_3', 'comments_3', 'reel_url_4', 'views_4', 'likes_4', 'comments_4']

,reel_url_1,views_1,likes_1,comments_1,reel_url_2,views_2,likes_2,comments_2,reel_url_3,views_3,likes_3,comments_3,reel_url_4,views_4,likes_4,comments_4
0,https://www.instagram.com/cosmicskeptic/reel/C...,170000,9862,5600000,https://www.instagram.com/cosmicskeptic/reel/C...,7263,705,428000,https://www.instagram.com/cosmicskeptic/reel/C...,12600,675,653000,https://www.instagram.com/cosmicskeptic/reel/C...,6566,1672,295000
1,https://www.instagram.com/cosmicskeptic/reel/C...,3813,394,197000,https://www.instagram.com/cosmicskeptic/reel/C...,19900,1621,1100000,https://www.instagram.com/cosmicskeptic/reel/C...,58600,1324,1300000,https://www.instagram.com/cosmicskeptic/reel/C...,2220,12,92900
2,https://www.instagram.com/cosmicskeptic/reel/C...,2385,18,90900,https://www.instagram.com/cosmicskeptic/reel/C...,4908,403,250000,https://www.instagram.com/cosmicskeptic/reel/C...,14400,1285,738000,https://www.instagram.com/cosmicskeptic/reel/C...,11300,263,390000
3,https://www.instagram.com/cosmicskeptic/reel/C...,4668,337,168000,https://www.instagram.com/cosmicskeptic/reel/C...,3748,257,154000,https://www.instagram.com/cosmicskeptic/reel/C...,3735,108,137000,https://www.instagram.com/cosmicskeptic/reel/C...,19900,242,837000
4,https://www.instagram.com/cosmicskeptic/reel/C...,20400,930,649000,https://www.instagram.com/cosmicskeptic/reel/C...,17400,2527,414000,https://www.instagram.com/cosmicskeptic/reel/C...,12300,430,406000,https://www.instagram.com/cosmicskeptic/reel/C...,34600,434,1100000

In [177]:
output_path = cleaned_folder / f"{input_path.stem}_cleaned.csv"
cleaned_df.to_csv(output_path, index=False)

print(f"✅ Cleaned and saved: {output_path.name}")

✅ Cleaned and saved: instagram (23)_cleaned.csv

Merge all the instagram cleaned files

In [196]:
import pandas as pd
from pathlib import Path

# Set folder paths
cleaned_folder = Path(r"C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\instagram\instagram_comments_cleaned")
output_path = cleaned_folder.parent / "instagram_comments_merged.csv"

# Get all cleaned files
cleaned_files = list(cleaned_folder.glob("*_cleaned.csv"))

if not cleaned_files:
    print("❌ No cleaned files found in the folder")
else:
    print(f"🔍 Found {len(cleaned_files)} cleaned files to merge")
    
    # Read and concatenate all files
    dfs = []
    for file in cleaned_files:
        try:
            df = pd.read_csv(file)
            dfs.append(df)
            print(f"✅ Loaded {file.name}")
        except Exception as e:
            print(f"❌ Failed to load {file.name}: {str(e)}")
    
    if dfs:
        merged_df = pd.concat(dfs, ignore_index=True)
        
        # Remove potential duplicates
        initial_count = len(merged_df)
        merged_df = merged_df.drop_duplicates(subset=['username', 'comment', 'comment_url'], keep='first')
        final_count = len(merged_df)
        
        # Save merged file
        merged_df.to_csv(output_path, index=False)
        print(f"\n🎉 Successfully merged {len(dfs)} files")
        print(f"📊 Initial rows: {initial_count:,}")
        print(f"📊 Final rows after deduplication: {final_count:,}")
        print(f"💾 Saved to: {output_path}")
    else:
        print("❌ No valid DataFrames to merge")

🔍 Found 39 cleaned files to merge
✅ Loaded cleaned_instagram_data_cleaned.csv
✅ Loaded instagram (1)_cleaned.csv
✅ Loaded instagram (10)_cleaned.csv
✅ Loaded instagram (11)_cleaned.csv
✅ Loaded instagram (12)_cleaned.csv
✅ Loaded instagram (13)_cleaned.csv
✅ Loaded instagram (14)_cleaned.csv
✅ Loaded instagram (15)_cleaned.csv
✅ Loaded instagram (16)_cleaned.csv
✅ Loaded instagram (17)_cleaned.csv
✅ Loaded instagram (18)_cleaned.csv
✅ Loaded instagram (19)_cleaned.csv
✅ Loaded instagram (2)_cleaned.csv
✅ Loaded instagram (20)_cleaned.csv
✅ Loaded instagram (21)_cleaned.csv
✅ Loaded instagram (22)_cleaned.csv
✅ Loaded instagram (23)_cleaned.csv
✅ Loaded instagram (24)_cleaned.csv
✅ Loaded instagram (25)_cleaned.csv
✅ Loaded instagram (26)_cleaned.csv
✅ Loaded instagram (27)_cleaned.csv
✅ Loaded instagram (3)_cleaned.csv
✅ Loaded instagram (4)_cleaned.csv
✅ Loaded instagram (5)_cleaned.csv
✅ Loaded instagram (6)_cleaned.csv
✅ Loaded instagram (7)_cleaned.csv
✅ Loaded instagram (9)_cleaned.csv
✅ Loaded instagram freewill_cleaned.csv
✅ Loaded instagram grief1_cleaned.csv
✅ Loaded instagram grief2 (2)_cleaned.csv
✅ Loaded instagram grief2_cleaned.csv
✅ Loaded instagram grief3_cleaned.csv
✅ Loaded instagram grief_cleaned.csv
✅ Loaded instagram loneliness_cleaned.csv
✅ Loaded instagram morality_cleaned.csv
✅ Loaded instagram no love_cleaned.csv
✅ Loaded instagram_cleaned.csv
✅ Loaded instagram_consciousness_cleaned.csv
✅ Loaded instagram_consciousness_sam_harris_cleaned.csv

🎉 Successfully merged 39 files
📊 Initial rows: 13,259
📊 Final rows after deduplication: 9,993
💾 Saved to: C:\Users\USER\Desktop\Projects\philosophy_and_popculture\data\pop_texts\instagram\instagram_comments_merged.csv